### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by dallaselynn**

### CODE REVIEW

**Review by naoko — APPROVED** [review]
This is intimidating for me :sweat_drops:  so I thought of what I can contribute :eyes: 
I ran `make` to build then run through an example and it all worked!
I ran `mix test` and wasn't successful so any guidance would be appreciated!

```
➜  annoy_ex git:(Ongoing-Work) ✗ mix test
make: 'priv/annoy.so' is up to date.

== Compilation error in file test/angular_index_test.exs ==
** (SyntaxError) test/angular_index_test.exs:13:52: syntax error before: '*'
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by dallaselynn** [comment]
Very strange!  I am using Elixir 1.13 - I will try to install 1.12 with asdf and see if I get the same, maybe I need to update the required version.

Is this what the top of your test/angular_index_test.ex looks like:

```
defmodule AnnoyExAngularIndexTest do
  use ExUnit.Case, async: true
  import AnnoyTestHelper

  defp check_precision(n, n_trees \\ 10, n_points \\ 10000, n_rounds \\ 10, search_k \\ 100_000) do
    founds =
      for _r <- 0..(n_rounds - 1) do
        f = 10
        i = AnnoyEx.new(f, :angular)

        for j <- 0..(n_points - 1) do
          p = normal_list(f - 1)
          norm = Enum.sum(Enum.map(p, fn pi -> pi ** 2 end)) ** 0.5

```

**Comment by dallaselynn** [comment]
Okay so it turns out that `**` was introduced in Elixir 1.13.  I've updated the tests to work in 1.12.

**Comment by naoko** [comment]
> Okay so it turns out that `**` was introduced in Elixir 1.13. I've updated the tests to work in 1.12.

Yay, thank you! All tests ran successfully!
```
Finished in 55.4 seconds (55.4s async, 0.00s sync)
87 tests, 0 failures
```
